on:
  push:
    branches: [ 'main' ]
    tags: [ '*' ]

jobs:
  build-and-publish-container-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #=========================================================#
        # NOTE: update these as dockerfiles are added to the repo #
        #=========================================================#
        image: [
            'pandoc-full',
            'wkhtmltopdf',
            'mdbook'
          ]

    permissions:
      contents: read
      packages: write

    steps:

      #===========================#
      # Always checkout and build #
      #===========================#
      - uses: actions/checkout@v3
      - name: Build Container Image
        run: ./build.sh ${{ matrix.image }}

      #=============================================#
      # Only publish images when commits are tagged #
      #=============================================#

      # GitHub Container Repo
      - uses: docker/login-action@v2
        #if: github.ref_type == 'tag' #TODO: uncomment after verifying login
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Define full image tag
        #if: github.ref_type == 'tag' #TODO: uncomment after verifying login
        id: ghcr
        run: echo "image=ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}" >> $GITHUB_OUTPUT
      - name: Tag and Push to GitHub Container Repository
        if: github.ref_type == 'tag'
        run: |
          docker tag \
            ${{ matrix.image }} \
            ${{ steps.ghcr.outputs.image }}:latest
          docker tag \
            ${{ matrix.image }} \
            ${{ steps.ghcr.outputs.image }}:${{ github.ref_name }}
          docker push --all-tags \
            ${{ steps.ghcr.outputs.image }}

      # Docker Hub
      - uses: docker/login-action@v2
        #if: github.ref_type == 'tag' #TODO: uncomment after verifying login
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Define full image tag
        #if: github.ref_type == 'tag' #TODO: uncomment after verifying login
        id: dockerhub
        run: echo "image=${{ secrets.DOCKER_USERNAME }}/${{ matrix.image }}" >> $GITHUB_OUTPUT
      - name: Tag and Push to Docker Hub
        if: github.ref_type == 'tag'
        run: |
          docker tag \
            ${{ matrix.image }} \
            ${{ steps.dockerhub.outputs.image }}:latest
          docker tag \
            ${{ matrix.image }} \
            ${{ steps.dockerhub.outputs.image }}:${{ github.ref_name }}
          docker push --all-tags \
            ${{ steps.dockerhub.outputs.image }}
